/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'apps-clients-list': RouteRecordInfo<'apps-clients-list', '/apps/clients/list', Record<never, never>, Record<never, never>>,
    'apps-disenos-create': RouteRecordInfo<'apps-disenos-create', '/apps/disenos/create', Record<never, never>, Record<never, never>>,
    'apps-disenos-edit-id': RouteRecordInfo<'apps-disenos-edit-id', '/apps/disenos/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-disenos-list': RouteRecordInfo<'apps-disenos-list', '/apps/disenos/list', Record<never, never>, Record<never, never>>,
    'apps-pedidos-create': RouteRecordInfo<'apps-pedidos-create', '/apps/pedidos/create', Record<never, never>, Record<never, never>>,
    'apps-pedidos-edit-id': RouteRecordInfo<'apps-pedidos-edit-id', '/apps/pedidos/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-pedidos-list': RouteRecordInfo<'apps-pedidos-list', '/apps/pedidos/list', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
