import type { ThemeDefinition } from 'vuetify'

// 🎨 18D JOYEROS – Paleta de marca extraída del logo
// Dorado principal: #C9A84C | Dorado claro: #E2C06A | Dorado oscuro: #A07A2B
// Negro profundo: #141414 | Negro superficie: #1E1B16 | Crema: #F7F3EC

export const staticPrimaryColor = '#C9A84C'
export const staticPrimaryDarkenColor = '#A07A2B'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#141414',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#6B6355',
      'on-secondary': '#fff',
      'secondary-darken-1': '#564F44',
      'success': '#2DAF6B',
      'on-success': '#fff',
      'success-darken-1': '#259D5F',
      'info': '#1A96B0',
      'on-info': '#fff',
      'info-darken-1': '#167F96',
      'warning': '#D4820A',
      'on-warning': '#fff',
      'warning-darken-1': '#BA7209',
      'error': '#D93025',
      'on-error': '#fff',
      'error-darken-1': '#BF2921',
      'background': '#F7F3EC',
      'on-background': '#1E1B16',
      'surface': '#FFFFFF',
      'on-surface': '#1E1B16',
      'grey-50': '#FAF8F4',
      'grey-100': '#F2EDE4',
      'grey-200': '#E8E1D6',
      'grey-300': '#D6CCBE',
      'grey-400': '#B8ADA0',
      'grey-500': '#8C8070',
      'grey-600': '#6B6355',
      'grey-700': '#4F4840',
      'grey-800': '#332E28',
      'grey-900': '#1E1B16',
      'grey-light': '#FAF8F4',
      'perfect-scrollbar-thumb': '#D6CCBE',
      'skin-bordered-background': '#FFFFFF',
      'skin-bordered-surface': '#FFFFFF',
      'expansion-panel-text-custom-bg': '#FAF8F4',
    },

    variables: {
      'code-color': '#A07A2B',
      'overlay-scrim-background': '#1E1B16',
      'tooltip-background': '#1E1B16',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#1E1B16',
      'border-opacity': 0.1,
      'table-header-color': '#F2EDE4',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.65,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#EDE8DF',

      // Shadows
      'shadow-key-umbra-color': '#1E1B16',
      'shadow-xs-opacity': 0.08,
      'shadow-sm-opacity': 0.10,
      'shadow-md-opacity': 0.12,
      'shadow-lg-opacity': 0.14,
      'shadow-xl-opacity': 0.16,
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#0F0F11',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': '#A1A1AA',
      'on-secondary': '#0F0F11',
      'secondary-darken-1': '#71717A',
      'success': '#2DAF6B',
      'on-success': '#fff',
      'success-darken-1': '#259D5F',
      'info': '#1A96B0',
      'on-info': '#fff',
      'info-darken-1': '#167F96',
      'warning': '#D4820A',
      'on-warning': '#fff',
      'warning-darken-1': '#BA7209',
      'error': '#D93025',
      'on-error': '#fff',
      'error-darken-1': '#BF2921',
      'background': '#0F0F11',
      'on-background': '#F4F4F5',
      'surface': '#18181B',
      'on-surface': '#F4F4F5',
      'grey-50': '#18181B',
      'grey-100': '#222227',
      'grey-200': '#2C2C32',
      'grey-300': '#3F3F46',
      'grey-400': '#52525B',
      'grey-500': '#71717A',
      'grey-600': '#A1A1AA',
      'grey-700': '#D4D4D8',
      'grey-800': '#E4E4E7',
      'grey-900': '#F4F4F5',
      'grey-light': '#222227',
      'perfect-scrollbar-thumb': '#3F3F46',
      'skin-bordered-background': '#18181B',
      'skin-bordered-surface': '#18181B',
    },
    variables: {
      'code-color': '#E2C06A',
      'overlay-scrim-background': '#09090B',
      'tooltip-background': '#27272A',
      'overlay-scrim-opacity': 0.75,
      'hover-opacity': 0.08,
      'focus-opacity': 0.12,
      'selected-opacity': 0.1,
      'activated-opacity': 0.18,
      'pressed-opacity': 0.16,
      'dragged-opacity': 0.12,
      'disabled-opacity': 0.4,
      'border-color': '#FFFFFF',
      'border-opacity': 0.12,
      'table-header-color': '#222227',
      'high-emphasis-opacity': 0.92,
      'medium-emphasis-opacity': 0.68,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#222227',

      // Shadows
      'shadow-key-umbra-color': '#000000',
      'shadow-xs-opacity': 0.25,
      'shadow-sm-opacity': 0.30,
      'shadow-md-opacity': 0.35,
      'shadow-lg-opacity': 0.40,
      'shadow-xl-opacity': 0.45,
    },
  },
}

export default themes
